### ISSUE TITLE
No Playback on most servers: "Unsupported Server"

### ISSUE THREAD

**Issue by kodan2k** [groggyegg/plugin.video.dramacool#10]
Looks like files on "Standard Server", "Kvid", "Asianstream", "StreamSB" can't be opened. The rest is working:

2021-05-13 11:00:40.760 T:2996    ERROR <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.dramacool/mouse-2021-episode-18.html]

Tested with Kodi 19 on Windows with Dramacool Version 2.0.2.

[kodi.log](https://github.com/groggyegg/plugin.video.dramacool/files/6471496/kodi.log)

**Comment by groggyegg** [comment]
I have fixed the "Standard Server" and "Kvid" in my latest commit. I won't have time to add Asianstream, if someone is interested to add the resolver you can do it through pull request.

I have also made a pull request to resolveurl for StreamSB so it should be fixed in the next release.

**Comment by cbizzle14** [comment]
@groggyegg will this be fixed on older versions? I'm still running kodi 18.9 so I have to use dramacool version 1.8.5

**Comment by groggyegg** [comment]
> @groggyegg will this be fixed on older versions? I'm still running kodi 18.9 so I have to use dramacool version 1.8.5

I have already backported the patches to Kodi 18. You can install it from the sources.

**Comment by cbizzle14** [comment]
> > @groggyegg will this be fixed on older versions? I'm still running kodi 18.9 so I have to use dramacool version 1.8.5
> 
> I have already backported the patches to Kodi 18. You can install it from the sources.

Awesome. Appreciate your work!

**Comment by kodan2k** [comment]
"Standard Server" and "Kvid" working again with version 2.0.3 and 1.8.6. Thank you!
