### ISSUE TITLE
Standard server and kvid servers not working

### ISSUE THREAD

**Issue by cbizzle14** [groggyegg/plugin.video.dramacool#12]
Keep getting error when I try to use these two.

**Comment by kodan2k** [comment]
Add "StreamSB" and "Xstreamcdn" to the not working servers. At least for newer files. Tested with Version 2.0.3 on Kodi 19.
[kodi.log](https://github.com/groggyegg/plugin.video.dramacool/files/6688909/kodi.log)

**Comment by cbizzle14** [comment]
> Add "StreamSB" and "Xstreamcdn" to the not working servers. At least for newer files. Tested with Version 2.0.3 on Kodi 19.
> [kodi.log](https://github.com/groggyegg/plugin.video.dramacool/files/6688909/kodi.log)

Streamsb never works on 18.9 it always says unsupported server. Xstream is working for me tho on 18.9

**Comment by groggyegg** [comment]
It will probably take awhile to fix it since I don't have enough time to look into it. Some changes has been done in the standard and kvid mirrors which require some decryptions. For the time being, use other mirrors.

**Comment by cywteow** [comment]
Hi Groggyegg,

I've decrypted the url for standard server. However, they started to use captcha now, so gonna think of a way to bypass the captcha.

E.g
DramacoolUrl: https://www1.dramacool.ch/ichikei-no-karasu-2021-episode-11.html
Standard server url: https://asianload.io/streaming.php?id=MjYyODY4&title=Ichikei+no+Karasu+%282021%29+episode+11&typesub=SUB
Resolved: https://k-vid.co/download?id=MjYyODY4

MjYyODY4 is the id of the video

Hope it helps you.

**Comment by groggyegg** [comment]
> Hi Groggyegg,
> 
> I've decrypted the url for standard server. However, they started to use cloudflare captcha now, so gonna think of a way to bypass the captcha.
> 
> E.g
> DramacoolUrl: https://www1.dramacool.ch/ichikei-no-karasu-2021-episode-11.html
> Standard server url: https://asianload.io/streaming.php?id=MjYyODY4&title=Ichikei+no+Karasu+%282021%29+episode+11&typesub=SUB
> Resolved: https://k-vid.co/download?id=MjYyODY4
> 
> MjYyODY4 is the id of the video
> 
> Hope it helps you.

Hi cywteow,

Thanks for helping. Cloudflare captcha will be a bit more difficult to solve since it changes regularly. The only module that I know of which is capable of doing it is cloudscraper but it seems to require a premium plan so that is not an option. But I think I some ideas.

**Comment by groggyegg** [comment]
I have updated standard server and kvid with HDR sources, higher quality seems to require captcha which I won't be able to fix. But streamsb has been updated in the upstream (resolveurl) and the rest of the mirrors seems to work (except asianstream since I haven't added support for it).

**Comment by Zappano** [comment]
It seems all the other servers show as unsupported server in kodi 19. Only streamtape is working for now.

**Comment by cbizzle14** [comment]
> It seems all the other servers show as unsupported server in kodi 19. Only streamtape is working for now.

On 18.9 only xstream and streamtape work. Every thing was fine before I went to work last night night at 11 pm central. Come home to this

**Comment by kodan2k** [comment]
Can confirm. For me streamtape and mixdrop work. Rest unfortunately not. Tested with 2.0.4 on Kodi 19.
[kodi.log](https://github.com/groggyegg/plugin.video.dramacool/files/6748921/kodi.log)

**Comment by groggyegg** [comment]
I have just tested the mirrors. It seems that only the standard server and kvid is not working anymore but the rest is still working.

**Comment by kodan2k** [comment]
Ok, mirrors work again with resolveurl 5.1.35. I received an update for version 2.0.5 and now everything works again. Would be cool if you could also provide an update for older version 1.8.x. Thank you for all your efforts!

**Comment by groggyegg** [comment]
The server has been fixed in v2.1.0 and v1.8.8.

**Comment by groggyegg** [comment]
It seems that cloudflare captcha has been added to the standard server and kvid. My recommendation is to use other servers for the time being.

**Comment by cywteow** [comment]
Fixed encryption for standard server #40 
Please review.

**Comment by groggyegg** [comment]
Fixed in https://github.com/Gujal00/ResolveURL/commit/f03bc918a27d36e40c47bba9e3fe370f4be5c373
