### ISSUE TITLE
unsupported server message

### ISSUE THREAD

**Issue by Majdalina** [groggyegg/plugin.video.dramacool#14]
hello,
since yesterday everytime i want to use dramacool comes a message ,unsupported server, after selecting the server of viewing. i tried them all but nothing worked 
i have the latest cooldrama addon on kodi matrix.
thank you for everything

**Comment by groggyegg** [comment]
> I have just tested the mirrors. It seems that only the standard server and kvid is not working anymore but the rest is still working. Make sure that you have the latest resolveurl (5.1.33).

#12
