### ISSUE TITLE
Unable to install Version 2.2.1 (Kodi v19.3)

### ISSUE THREAD

**Issue by a-woo** [groggyegg/plugin.video.dramacool#20]
I previously had Version 2.2.0 installed from the Lime repository. I tried to install the update for Version 2.2.1 but all it did was remove 2.2.0 and the new version failed to install. I tried to install it again from the repository, but it looks like it just installs the dependencies but does not install the add-on. How do I go back to 2.2.0?

**Comment by donrusykodi** [comment]
Same as me here.. i using the dramacool as widget as well and out of sudden keep prompting me to download dramacool addon but after press install nothing happens and it keep asking me to download the dramacool addon again and again

**Comment by groggyegg** [comment]
Yes, there seems to be some issue with installation. Currently working with it.

**Comment by groggyegg** [comment]
Couldn't find any issue with the installations, but I did find some bug when trying to open the plugin. It's now fixed in 2.2.2, could someone check if the issue still exists or if it's fixed.

**Comment by a-woo** [comment]
> Couldn't find any issue with the installations, but I did find some bug when trying to open the plugin. It's now fixed in 2.2.2, could someone check if the issue still exists or if it's fixed.

Thanks, just tried installing 2.2.2 and it works fine. The only working servers are StreamSB and DoodStream, is this expected?
