### ISSUE TITLE
Search by star not working

### ISSUE THREAD

**Issue by cbizzle14** [groggyegg/plugin.video.dramacool#26]
Searching for an actor will produce a returned result but clicking on a name will return an error. Don't have a log because I just went to work. Also I tried searching for a variety show and get an error each time. I'm guessing because it can't find it but I know it's on their website. I've searched the full name and two alternate names and still won't return results.

**Comment by cbizzle14** [comment]
Https://paste.kodi.tv/ekinipamul

Hopefully this log has the errors in it

**Comment by groggyegg** [comment]
How did you install Kodi? Sqlite needs to be installed with json extension. Not sure if this is enabled by default in Kodi for Windows but at least it works in Ubuntu.

**Comment by cbizzle14** [comment]
Through the Xbox store. Recently watched was working fine last night but as soon as I found the show through recently added and watched some of it it stopped working. I don't know how long search hasn't been working but I know recently watched had been working fine for months

**Comment by cbizzle14** [comment]
So I completely uninstalled dramacool and removed related settings. Which worked but still get error when searching for this show. Unnies are running. But on my android device it finds it with no problems. Search by star still doesn't work. So something is wrong with the Xbox version which is just the windows version. I'm able to reproduce the error every time. As soon as I watch that show through recently added then recently watch doesn't work any more as well

https://paste.kodi.tv/iriredamux

**Comment by long-lo** [comment]
I have the same issue by installing Kodi from the Windows Store onto my Windows 10 PC.  I'm guessing XBox is pulling it from the same source.

**Comment by groggyegg** [comment]
It could be an issue with the changes made in the parser not long time ago. Regardless, the request code will be rewritten (under development) which should fix the problem. For now just wait.

**Comment by groggyegg** [comment]
It's now fixed in "DramaCool (Dev)" addon, the changes will be merged to stable release after testing.

**Comment by groggyegg** [comment]
Fixed in v2.3.x
