### ISSUE TITLE
No cover art in Matrix Favorites

### ISSUE THREAD

**Issue by xalagaco** [groggyegg/plugin.video.dramacool#30]
When you save a show in Favorites, cover art shows nicely in Leia, but you only get a big white star in Matrix.
I was hoping for a fix in 3.0.0, but no. I know it's a nitpick, but it's a much better user experience with them.

**Comment by groggyegg** [comment]
Fixed in v3.0.1

**Comment by xalagaco** [comment]
Nice! You da man.
