### ISSUE TITLE
"Recently Watched" home screen widget not display show name

### ISSUE THREAD

**Issue by stvg88** [groggyegg/plugin.video.dramacool#31]
Hi loving your addon so much!

Just 1 feedback: when I put "Recently Watched" folder as a homescreen widget, the show name is not displayed on top, and the cover art is displayed instead, which doesn't look very nice
![image](https://user-images.githubusercontent.com/20413268/171473656-2c21ffea-d613-4ce5-ad21-16ecd1fe6505.png)

My expectation is that it will look like this (manually created a widget using Super Favorites)
![image](https://user-images.githubusercontent.com/20413268/171474230-f7df81a5-cc2f-48ab-9883-5d7fe664f359.png)

Btw I'm using Cosmic skin on Kodi 19.3

**Comment by stvg88** [comment]
update: to fix this issue, i think just need to remove:
`'clearlogo': kwargs['poster'],`
from init function in Drama class in database.py

**Comment by groggyegg** [comment]
> update: to fix this issue, i **think** just need to remove: `'clearlogo': kwargs['poster'],` from init function in Drama class in database.py

Can you confirm if this actually solves the problem? I won't have time to test it so need confirmations that this actually solves it and doesn't break anything else before I do any change.

**Comment by stvg88** [comment]
@groggyegg yea i tried, it will revert to the default clearlogo, which is just the item name. It doesn't seem to break anything else. And based on your latest commit, seems like `clearlogo` was not set previously either, so that should be safe!

![image](https://user-images.githubusercontent.com/20413268/172016354-82fa8b43-66a4-44ba-b361-17a10863bcb3.png)
