### ISSUE TITLE
Not many working links in Leia

### ISSUE THREAD

**Issue by xalagaco** [groggyegg/plugin.video.dramacool#34]
V3.0.2 on Leia only has 2 links that work at all, Xstreamcdn & Streamtape.
For those shows where these two links don't work, you're out of luck, e.g. Pachinko, The Sound of Magic, etc.

All is well in Matrix, most links other than the top two, Standard Server & Asianload, work as usual.

**Comment by groggyegg** [comment]
All the resolvers has been moved to ResolveURL and it should work in both cases since it share the same code. Have you checked if the version of ResolveURL is the latest on Leia? Also, anyone is free to do a PR in ResolveURL to fix the non-working servers since I won't have time to fix it.

**Comment by xalagaco** [comment]
ResolveURL version was 5.1.67, upgrading to 5.1.69 did not help. Matrix is also at 5.1.69.
Before that only one link, Xstreamcdn, worked. I thought the improvement was due to V3.0.2.
So, are we thinking ResolveURL on Leia is the culprit?
It seems to work on Nightwing equally well for both Kodi versions based on a quick check.
But, then again they're hitting different servers. I'll go create a ticket over there.

**Comment by groggyegg** [comment]
Hard to say. Either there is an issue with py2/py3 compatible code in peewee or it could be related to ResolveURL. Easiest way to find the issue would be to log and track the error.

Could you provide an example of the drama and episode that have the issue? I will look into it when I have time.

**Comment by xalagaco** [comment]
soupsieve? All dramas/episodes exhibit the same symptom, e.g., Our Blues Episode 1.

> 2022-06-16 15:30:09.893 T:19437 ERROR: DoWork - Direct texture file loading failed for androidapp://sources/apps/com.amazon.ftv.screensaver.png
> 2022-06-16 15:29:57.820 T:31082 ERROR: Playlist Player: skipping unplayable item: 19, path [plugin://plugin.video.dramacool/our-blues-2022-episode-1.html] 'The soupsieve package is not installed. CSS selectors cannot be used.'
> .
> .
> 2022-06-16 15:28:57.067 T:19250 ERROR:
> /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.beautifuls UserWarning: The soupsieve package is not installed. CSS selectors cannot be used.
> 2022-06-16 15:28:56.701 T:19255 ERROR: InputStream: Error opening, plugin://plugin.video.dramacool/our-blues-2022-episode-19.html
> 2022-06-16 15:28:56.699 T:19255 ERROR: InputStream: Error opening, plugin://plugin.video.dramacool/our-blues-2022-episode-18.html
> .
> .
> 2022-06-16 15:28:41.960 T:31082 ERROR: Playlist Player: skipping unplayable item: 19, plugin://plugin.video.dramacool/our-blues-2022-episode-20.html path [plugin://plugin.video.dramacool/our-blues-2022-episode-1.html] 'The soupsieve package is not installed. CSS selectors cannot be used.'
> 2022-06-16 15:28:35.675 T:19235 ERROR: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.beautifuls UserWarning: The soupsieve package is not installed. CSS selectors cannot be used.
> 2022-06-16 15:28:26.526 T:31082 NOTICE: VideoPlayer: finished waiting
> 2022-06-16 15:28:26.526 T:31082 NOTICE: VideoPlayer: waiting for threads to exit
> 2022-06-16 15:28:26.525 T:31082 NOTICE: CVideoPlayer::CloseFile()
> 2022-06-16 15:28:26.525 T:31082 NOTICE: VideoPlayer: finished waiting
> 2022-06-16 15:28:26.488 T:31094 NOTICE: CAESinkAUDIOTRACK::Initializing with:
> 2022-09-20 19:20:20 m_sampleRate: 44100 format: AE_FMT_FLOAT (AE) method: PCM stream-type: PCM-STREAM min_buffer_size: 22688 m_frames: 1418 m_frameSize: 8 channels: 2
> 2022-06-16 15:28:26.478 T:31094 NOTICE: Trying to open: samplerate: 44100, channelMask: 12, encoding: 4 2022-06-16 15:28:26.444 T:19210 NOTICE: thread end: video_thread
> 2022-06-16 15:28:26.413 T:19195 NOTICE: waiting for video thread to exit
> 2022-06-16 15:28:26.413 T:19195 NOTICE: Closing stream player 2 NOTICE: Deleting audio codec
> 2022-06-16 15:28:26.412 T:19195
> 2022-06-16 15:28:26.365 T:19195 NOTICE: Closing audio device
> 2022-06-16 15:28:26.364 T:19213 NOTICE: thread end: CVideoPlayerAudio::OnExit()
> 2022-06-16 15:28:26.353 T:19195 NOTICE: Waiting for audio thread to exit
> 2022-06-16 15:28:26.353 T:19195 NOTICE: Closing stream player 1
> 2022-06-16 15:28:26.353 T:19195
> 2022-06-16 15:28:26.345 T:31082 NOTICE: VideoPlayer: waiting for threads to exit NOTICE: CVideoPlayer::OnExit()
> 2022-06-16 15:28:26.342 T:31082 NOTICE: CVideoPlayer::CloseFile()
> 2022-06-16 15:28:26.323 T:31082 ERROR: Playlist Player: skipping unplayable item: 19, path [plugin://plugin.video.dramacool/our-blues-2022-episode-1.html] cannot be used." The soupsleve package is not installed. CSS selectors
> 2022-06-16 15:28:20.096 T:19219 ERROR: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.beautifuls UserWarning: The soupsieve package is not installed. CSS selectors cannot be used.
> 2022-06-16 15:28:15.692 T:31082 ERROR: Control 55 in window 10025 has been asked to focus, but it can't

**Comment by xalagaco** [comment]
Here's the [log](https://paste.kodi.tv/ojacuhihid) when I tried the Doodstream link of Our Blues E1.
When I tried the [URL](https://dood.ws/d/fl62zfpzsyss) in the SMR Link Tester, the video plays just fine in Leia.
So, at this point ResolveURL is off the hook. I'll be closing that ticket.

**Comment by groggyegg** [comment]
I have looked into the issue. It seems that the url is being resolved by ResolveUrl but Kodi 18.9 is unable to play the video with the provided link so it might just be a limitation with the older playback. Have this worked before?

**Comment by xalagaco** [comment]
But the link plays fine in SMR Link Tester within 18.9, just not in DramaCool.
I was expecting the link would fail to play in 18.9 and succeed in 19.4, then have ResolveURL fix it.
Well, that didn't work out as planned. It must be within DramaCool somewhere.

I do remember everything working as before when you first combined the  two branches, 3.0.0, I was quite tickled.
Then one day, all servers other than Xstreamcdn fails to play, a few days later Streamtape starts working again.
My thinking was they were 3.0.1 and 3.0.2 related, although I don't know if they actually correlate.
