### ISSUE TITLE
Dramacool kodi add on 3.0.3 not showing video folders

### ISSUE THREAD

**Issue by abikeaway** [groggyegg/plugin.video.dramacool#38]
When going into any menu section, I am not seeing any episodes or folders.

**Comment by cbizzle14** [comment]
Currently using it now with no issues. Is resolveurl all the way updated?

**Comment by abikeaway** [comment]
I went to manage decencies and checked and resolveurl is 5.1.70.

**Comment by stvg88** [comment]
@abikeaway the addon pulls data from these 2 websites: watchasian.sh, www1.dramacool.fo
You should try to see if you can access these 2 websites or not, it's possible your ISP has blocked it

**Comment by Dor1813** [comment]
Www1 dramacool.ee is working as of this morning. The rest all doesn't work

**Comment by Dor1813** [comment]
This is the url:
https://www1.dramacool.ee/

**Comment by stvg88** [comment]
ok, then i think you face the same problem as me @Dor1813 , where our ISP blocks watchasian.sh (but doesn't block www1.dramacool.fo or www1.dramacool.ee). So what I did is I manually removed 'watchasian.sh' from the list of domains in `request.py` file.

@groggyegg I think in your `Request.get` method, this line is throwing `SSLError` if the network blocks access to the site. I guess you can either add arg `verify=False`, or a try-except block to catch it:
`response = self.session.get('https://{}{}'.format(domain, path))`

**Comment by groggyegg** [comment]
Cool, `verify=False` is probably the preferred way.
Also, is [www1.dramacool.ee/](https://www1.dramacool.ee/) compatible with the existing parser?

Will probably fix this during the weekend if no PR is up.

**Comment by stvg88** [comment]
@groggyegg yes, in fact `www1.dramacool.fo` redirects to `www1.dramacool.ee`, and my addon is still working well with only `www1.dramacool.fo` enabled

```
>>> response = session.get('https://{}'.format('www1.dramacool.fo`), verify=False)
>>> response.url
'https://www1.dramacool.ee/'
```

**Comment by groggyegg** [comment]
Can someone verify if this issue has been fixed in latest version?

**Comment by abikeaway** [comment]
Somehow the fix worked for me.  I can see episodes and folders now.

**Comment by Dor1813** [comment]
Thanks so much @groggyegg for fixing everything.  Now it's working well.
