### ISSUE TITLE
Request: library integration

### ISSUE THREAD

**Issue by sflix** [groggyegg/plugin.video.dramacool#43]
Hello,
Could it be possible to add a library integration to the addon?

**Comment by groggyegg** [comment]
What kind of library?

**Comment by sflix** [comment]
kodi library integration

**Comment by groggyegg** [comment]
Which library addon and what improvement does it add to the addon?

**Comment by rahaaatul** [comment]
> Which library addon and what improvement does it add to the addon?

Think he was talking about local library integration.

If the file exist locally, use that instead of streaming from dramacool.

**Comment by groggyegg** [comment]
> > Which library addon and what improvement does it add to the addon?
> 
> Think he was talking about local library integration.
> 
> If the file exist locally, use that instead of streaming from dramacool.

Ok, thanks. This seems to be some special use case and will most likely not be implemented.
