### ISSUE TITLE
Disable English subtitle.

### ISSUE THREAD

**Issue by Uka-Uka** [groggyegg/plugin.video.dramacool#46]
Hello! I'm new to Kodi world and this my first add-on to try. It's very rich and helpful. Thanks for your work.

I'm facing only one issue related to the subtitle. I can't seem to be able to disable the English subtitle. Is it hardcoded? It interferes with my external sub makes it hard to read.

**Comment by groggyegg** [comment]
Subtitles are mostly hardcoded. External subtitles only happens on newly released video but are later turned to hardcoded.
