### ISSUE TITLE
Dramacool addon not retrieving episode from server

### ISSUE THREAD

**Issue by TroubledWaffle** [groggyegg/plugin.video.dramacool#53]
![image](https://user-images.githubusercontent.com/126484656/221580571-fc6ddd72-e6d2-430d-8567-31621a8bfed8.png)
I have trouble to load dramacool server. It can load the drama or movies available but when I click on it to view the episode available, it just won't load... I tried install kodi on my pc and it is working fine. I had tried rollback to 19, reset tv factory setting, reinstall kodi, clear cache but it is still not working. Problem only with dramacool. Other addon are working fine.

**Comment by mikeyipdotcom** [comment]
faced the same issue.

**Comment by TroubledWaffle** [comment]
@groggyegg, it is not working after your update. Thanks! :)
