### ISSUE TITLE
Older episodes of running man freeze kodi

### ISSUE THREAD

**Issue by cbizzle14** [groggyegg/plugin.video.dramacool#57]
https://paste.kodi.tv/zadipusuro

Can't watch any of the first 200+ episodes of running man to a certain point. Randomly tried 267 and that episode played but from 1-220 I get the freeze. As soon as you click any server you hear the audio and see the spinning wheel and then it just freezes. Can only completely close kodi to exit. This is happening on 20.1 and on Xbox. Doesn't have this problem on Android

This didn't use to be a problem because I've watched some of those episodes and they worked.

**Comment by groggyegg** [comment]
Hard to know what the issue is from the log. Could you test it again with Debug mode enabled and repload the log file?

**Comment by cbizzle14** [comment]
> Hard to know what the issue is from the log. Could you test it again with Debug mode enabled and repload the log file?

I turned on debug logging and tried to play the episode and it froze kodi. Using kodi logfile up loader to get log

Https://paste.kodi.tv/pesopivefu

**Comment by groggyegg** [comment]
> > Hard to know what the issue is from the log. Could you test it again with Debug mode enabled and repload the log file?
> 
> I turned on debug logging and tried to play the episode and it froze kodi. Using kodi logfile up loader to get log
> 
> [Https://paste.kodi.tv/pesopivefu](Https://paste.kodi.tv/pesopivefu)

Thanks. I have looked through the log and there doesn't seems to be any issue with the addon. Have you tested changing "Settings -> Player -> Videos -> Render method" to DXVA? Because there seems to be an issue with Auto detect in Xbox.

**Comment by cbizzle14** [comment]
That did it! I remember reading that weeks ago but didn't think it effected dramacool because it's different from most addons plus never had playback issues with it. While I got you here is it possible to for you to do the thing to update the titles and posters? Much appreciation for your work on this addon and your help!

**Comment by groggyegg** [comment]
There is some ongoing work regarding that but I haven't had time to work with it. I will try to get it merged this month.

**Comment by cbizzle14** [comment]
No problem. Thank you again for all you do
