### ISSUE TITLE
add cantonese voice dub content

### ISSUE THREAD

**Issue by gitcano** [groggyegg/plugin.video.dramacool#6]
it is very tiring to read subtitles.  Unfortunately there is no English voice dub content in existence today.  However there are thousands of professional cantonese dub dramas for korean japanese thai and other countries original movies/TV content,  Can you create a section for cantonese voice dub content like ICDrama has?

**Comment by groggyegg** [comment]
I think you are a bit confused on how this add-on works. This add-on can only fetch videos from DramaCool and display it on Kodi. It has no control over the videos/subtitles being uploaded to the website. So the request you are asking for is not possible.

The only Cantonese video that contains in this add-on is videos from Hong Kong which has it's own section. So I recommend you to watch Cantonese videos in ICDrama and if you want to watch the latest videos with English subtitles then use this add-on.
