### ISSUE TITLE
[Feature] Sorting for episodes

### ISSUE THREAD

**Issue by rahaaatul** [groggyegg/plugin.video.dramacool#60]
### Description
Sort Episodes Descending/Ascending by episodes. 

### Issue
For starter, if it begins with the last episode, it doesn't look good and the option to sort it from first to last does not work with theme. Currently it's in descend order. eg. 12 to 1. It would be better if it's in ascend order by default eg. from 1 to 12.

### Screen Recording

https://github.com/groggyegg/plugin.video.dramacool/assets/86149861/1df77ea9-f107-4114-88dc-40510c6f14de

**Comment by groggyegg** [comment]
Seems to be a bug

**Comment by groggyegg** [comment]
Fixed with [v3.2.1](https://github.com/groggyegg/plugin.video.dramacool/commit/3c67090c6268d6b944f26b37dba04078beab3b22)

**Comment by rahaaatul** [comment]
You're really fast! thanks groggy egg!
