### ISSUE TITLE
Unable to retrieve anything from Dramacool

### ISSUE THREAD

**Issue by TroubledWaffle** [groggyegg/plugin.video.dramacool#62]
**Describe the bug**

**To Reproduce**
1. Go to 'Dramacool'
2. Click on 'new drama/new movie/previously saved favourite'
3. Have error where unable to show anything : Photo of log as below.

![photo_2023-10-19_19-50-58](https://github.com/groggyegg/plugin.video.dramacool/assets/126484656/ecf14d04-f0b0-47c1-8adc-3288357e8a55)
![photo_2023-10-19_19-50-54](https://github.com/groggyegg/plugin.video.dramacool/assets/126484656/902f2a1b-5fb9-4c4a-b4c6-3a5c0ac52d54)
![photo_2023-10-19_19-51-01](https://github.com/groggyegg/plugin.video.dramacool/assets/126484656/58cff1b1-4b7a-4c8d-9443-2b739ac31a88)
![photo_2023-10-19_19-51-00](https://github.com/groggyegg/plugin.video.dramacool/assets/126484656/5bc06592-1aa2-4fd8-929b-d7845922b336)

**Comment by TroubledWaffle** [comment]
> Difficult to know the issue. You would have to upload the whole log. But the recommendation is to remove xbmcext and dramacool and reinstall dramacool.

I tried to remove and reinstall dramacool but now i'm getting different error "unable to connect to domain"
attached is the log.

[Kodilog.txt](https://github.com/groggyegg/plugin.video.dramacool/files/13113974/Kodilog.txt)

**Comment by TroubledWaffle** [comment]
[kodi.log](https://github.com/groggyegg/plugin.video.dramacool/files/13164466/kodi.log)
This is from my pc which have a different error >.<

**Comment by groggyegg** [comment]
> I tried to remove and reinstall dramacool but now i'm getting different error "unable to connect to domain" attached is the log.
> 
> [Kodilog.txt](https://github.com/groggyegg/plugin.video.dramacool/files/13113974/Kodilog.txt)

> [kodi.log](https://github.com/groggyegg/plugin.video.dramacool/files/13164466/kodi.log) This is from my pc which have a different error >.<

Both of them seems to indicate that you have redirecting issue to the domain.

**Comment by groggyegg** [comment]
Could you try the latest version and see if that solves the issue?

**Comment by TroubledWaffle** [comment]
> Could you try the latest version and see if that solves the issue?

It is now working!! :) 
Many thanks for the hard work. Much appreciated :)

**Comment by TroubledWaffle** [comment]
Hi groggy, seems like the problem keep coming back. I hereby attached logfile for your reference. Can you let me know what can I do to avoid such problem again? :D[
[Uploading Kodilog_221223.txt…]()
](url)
