### ISSUE TITLE
Dramacool 3.2.3 not providing output of data

### ISSUE THREAD

**Issue by TroubledWaffle** [groggyegg/plugin.video.dramacool#65]
**Describe the bug**
Unable to retrieve any info from Dramacool such as "Search Drama/Star/Recently Added Drama/ previously added in Favourites"

**To Reproduce**
Go to 'Dramacool'
Click on 'new drama/new movie/previously saved favourite'
Have error where unable to show anything : Log attached

**Expected behavior**
Would be able to retrieve info from "Search Drama/Star/Recently Added Drama/ previously added in Favourites" and show server to choose from when clicking them

**Log file**
[Kodilog_221223.txt](https://github.com/groggyegg/plugin.video.dramacool/files/13748413/Kodilog_221223.txt)

**Additional context**
This might be a repetitive issue as reported before : https://github.com/groggyegg/plugin.video.dramacool/issues/62.
May I know what is the issue and can I do anything to prevent them again? :D

Thanks

**Comment by TroubledWaffle** [comment]
> @TroubledWaffle your add-on still on 3.2.1 on your log.
It's weird then.. Here is the snip.
![Screenshot](https://github.com/groggyegg/plugin.video.dramacool/assets/126484656/09a8d3e6-7049-4824-a952-31431ea384cd)

**Comment by groggyegg** [comment]
It's possible to add a custom domain in addon settings. Have you tried that?

**Comment by TroubledWaffle** [comment]
> It's possible to add a custom domain in addon settings. Have you tried that?

I have not but I saw 2 over there.
Domain 1 - watchasian.sk
Domain 2 - dramacool.pa

**Comment by groggyegg** [comment]
Those are the default domains that are used for finding dramas. If you have issue with any of the domain then you should try to change it. For example

watchasian.sk -> www.watchasian.sk
dramacool.pa -> dramacool.com.pa

or other domains that are compatible with the addon.

**Comment by groggyegg** [comment]
> **Additional context** This might be a repetitive issue as reported before : #62. May I know what is the issue and can I do anything to prevent them again? :D

Sometimes the URL will be changed to something else. When that happens the old URL will be redirected to the new URL and that's the issue you have. The URL redirection is not working.

Or it could be that the domain is blocked by your ISP.

**Comment by TroubledWaffle** [comment]
> Those are the default domains that are used for finding dramas. If you have issue with any of the domain then you should try to change it. For example
> 
> watchasian.sk -> [www.watchasian.sk](http://www.watchasian.sk) dramacool.pa -> dramacool.com.pa
> 
> or other domains that are compatible with the addon.

I have tried the example that you provided and it is working now but the loading is taking extremely long time. When I go to a favorite or search for a drama, it takes maybe 10 minutes. Once the server option is up, it is fine..

aside from that, may I know where can I get the list of compatible domain with the addon please?

Here is the latest log 
[Kodilog_231223_TV.txt](https://github.com/groggyegg/plugin.video.dramacool/files/13757426/Kodilog_231223_TV.txt)

Thanks

**Comment by groggyegg** [comment]
Search can take a long time if new drama has not been stored in database but should be faster next time you search.

I don't know any other domains, you would have to look for them.

**Comment by groggyegg** [comment]
Closing this as this is not an addon bug.
