### ISSUE TITLE
Request - Kodi 17.6 compatibility

### ISSUE THREAD

**Issue by DoubleAsterisks** [groggyegg/plugin.video.dramacool#71]
I have a old Android 4.4.2 TV box. The highest compatible Kodi version I can find is "KODI 17.6 NON NEON FOR Tegra 2 and Android 4.0.3" and "FTMC". Both have older versions of python (i.e. 2.x).

Dramacool Addon installs but won't load.

I have checked the Kodi logs and made a few changes but I am stuck on line 100 in the database.py file. 

I am not sure how to change the double asterisks to make it compatible with python 2. Any advise on how to fix this error?

SyntaxError: ('invalid syntax', ('/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.dramacool/dramacool/database.py', 100, 62, '                    Drama.create(**Request.drama_detail(path), category=category)\n'))

Changes I have made so far are the following.

1) plugin.video.dramacool/dramacool/addon.py

Line 222:
#plugin.redirect(f'{plugin.path}/{characters}/{genres}/{statuses}/{years}')
plugin.redirect('{}/{}/{}/{}/{}'.format(plugin.path,characters,genres,statuses,years))

2) script.module.xbmcext/xbmcext/__init__.py

Line 29:
#import pathlib
import errno

Line 807:
#path = pathlib.Path(os.path.join(getAddonPath(), 'resources/data/resource.resx'))
#path.parent.mkdir(parents=True, exist_ok=True)
path = os.path.join(getAddonPath(), 'resources/data/resource.resx')
pathparent = os.path.join(getAddonPath(), 'resources/data')
try:
   os.makedirs(pathparent)
except OSError as e:
  if e.errno != errno.EEXIST:
    raise

**Comment by groggyegg** [comment]
`v = Request.drama_detail(path)`
`v[category] = category`
Drama.create(v)

**Comment by DoubleAsterisks** [comment]
Thanks that fixed the error.

Could you advise how to fix line 799 to make it compatible with python 2.

`File "C:\Users\Test\AppData\Roaming\Kodi\addons\script.module.xbmcext\.\xbmcext\__init__.py", line 799 in __init__
                                                super().__init__()
                                            TypeError: super() takes at least 1 argument (0 given)
`


Here are the other changes I made.


1. plugin.video.dramacool/dramacool/addon.py

Your fix on line 100:
`
# Drama.create(**Request.drama_detail(path), category=category)\n'))
v = Request.drama_detail(path)
v['category'] = category
Drama.create(v)
`
2. plugin.video.dramacool/dramacool/database.py

Added to line 36:
`try:
    TimeoutError  # >= Python 3.3
except NameError:
    TimeoutError = OSError  # < Python 3.3`

3. plugin.video.dramacool/dramacool/request.py

Replaced line 29:
`try:
  from urllib.error import URLError
except ImportError:
  from urllib2 import URLError`

4. script.module.xbmcext/xbmcext/init.py

Replaced line 818:
`getSettingString = Addon.getSetting`

Replaced the class on line 341 to 382:

`KODIVERSION = int(xbmc.getInfoLabel("System.BuildVersion")[:2])
if KODIVERSION >= 18:
    class ListItem(xbmcgui.ListItem):
        def __new__(cls, label='', label2='', iconImage='', thumbnailImage='', posterImage='', path='', offscreen=True):
            return super(ListItem, cls).__new__(cls, label, label2, path=path, offscreen=offscreen)

        def __init__(self, label='', label2='', iconImage='', thumbnailImage='', posterImage='', path='', offscreen=True):
            self.setArt({label: value for label, value in (('thumb', thumbnailImage), ('poster', posterImage), ('icon', iconImage)) if value})
else:
    class ListItem(xbmcgui.ListItem):
        def __new__(cls, label='', label2='', iconImage='', thumbnailImage='', posterImage='', path=''):
            return super(ListItem, cls).__new__(cls, label, label2, path=path)

        def __init__(self, label='', label2='', iconImage='', thumbnailImage='', posterImage='', path=''):
            self.setArt({label: value for label, value in (('thumb', thumbnailImage), ('poster', posterImage), ('icon', iconImage)) if value})`

**Comment by fredrik-sy** [comment]
Perhaps you need to define super(ResourceManager, self).init()

**Comment by DoubleAsterisks** [comment]
Thanks that line worked after adding underscore to init fuction.

```
super(ResourceManager, self).__init__()
```

The last changed I made to get add-on working in FTMC was the following.

```
    if KODIVERSION >= 17:
        SONG_USER_RATING = xbmcplugin.SORT_METHOD_SONG_USER_RATING
```
