### ISSUE TITLE
Standard and asianload server need fixing please

### ISSUE THREAD

**Issue by cbizzle14** [groggyegg/plugin.video.dramacool#75]
Some episodes are impossible to watch without these two servers as they're the only servers that show up for them. This applies to even newer episodes for example Flex x cop episode 5 only has those two servers so it's not possible to watch it. Another show I was watching didn't have the other severs for the second to last episode until like a month later. Standard server has been down for quite awhile now. Thank you for your hard work on this addon btw.

**Comment by vgupta1192** [comment]
yes many series and movies face this issue.
If possible kindly fix the issue

**Comment by groggyegg** [comment]
Too busy with other stuff. Fix needs to be done in another repo but not sure if encryption has changed or not otherwise it’s just domain update https://github.com/Gujal00/ResolveURL/blob/master/script.module.resolveurl/lib/resolveurl/plugins/dembed.py

**Comment by groggyegg** [comment]
Should be fixed in latest resolvurl now.



> I continue to get the resolveurl error message when I try to watch a show

Can you check resolvurl version?

**Comment by vgupta1192** [comment]
Its working now in latest version.
I have checked.
Thank you so much for the update.👍🏻

**Comment by groggyegg** [comment]
> Is it possible for you to create one for stremio application as well?

Sorry, it's too much work and I'm busy with my other projects so I won't have time for it.

Closing as this issue has been solved.
