### ISSUE TITLE
Not pulling server list from drama episode. It just keep trying to connect with "circle cursor"

### ISSUE THREAD

**Issue by Smrtmac** [groggyegg/plugin.video.dramacool#76]
It's not pulling server list from drama episode list. 
It just keep trying to connect with "circle cursor". Same thing happens with updated duboku plug-in. (with Kodi 20.x).
Is it just me? 

I'll try to link log file if needed.

**Comment by groggyegg** [comment]
Tested and works fine for me.

**Comment by Smrtmac** [comment]
Reinstalling Kodi fixed the problem.
Thank you.
