### ISSUE TITLE
List queries are failing

### ISSUE THREAD

**Issue by jeacott1** [groggyegg/plugin.video.dramacool#78]
Hi,
 first, thanks for a great addon!
lately however things are starting to fail. Drama list, Drama movies, and recently filtered no longer work.
It would be great if they could be restored.

Thank you.

**Comment by groggyegg** [comment]
It seems to work from my test. Have you tried to reinstall it?

**Comment by jeacott1** [comment]
@groggyegg No I haven't - I really don't want to lose my recently watched list which I use to capture what I have, and what I intend to watch. - I'm surprised those features still work for you, I assumed the api had changed a bit and broken this code. 
thanks.

**Comment by groggyegg** [comment]
Since when did this stop working? I only know that the user db was updated on 3.2.0. But if later version worked for you before then it might be other issue.

**Comment by groggyegg** [comment]
Regarding drama list/movies, these are stored in internal db that comes with the addon when installed/updated and should never be an issue.

**Comment by jeacott1** [comment]
@groggyegg re drama list and drama movies - I'm specifically talking about the search for these. It just fails. and whilst my recently my recently filtered search list exists the actual searches fail too.
When I select for example 'Korean Drama', then just hit done on the next screen I get an error in a popup toast 'on Conflict clause does not match any primary key'

This does indeed look like a local db issue - If you can tell me what sqllite db I'm looking in maybe I can identify the problem row(s) and fix them. I've commonly seen broken bits of various addons where something fails to write a primary key at all - maybe something similar is going on here?

**Comment by ameizeing** [comment]
I'm running Kodi 20.5 with Dramacool addon v3.2.8. When I try to list files for Drama, get error message "On CONFLICT does not match"

Log file uploaded at: https://paste.kodi.tv/miqipahixu

**Comment by groggyegg** [comment]
Closing since a workaround exist.
