### ISSUE TITLE
ResolveURL Error when trying to play any video

### ISSUE THREAD

**Issue by AcidSlide** [groggyegg/plugin.video.dramacool#79]
**Describe the bug**
When trying to play from the available sources, a ResolveURL error popup shows.

Kodi Version: 21.0
ResolveURL version: 5.1.136

**To Reproduce**
1. Go to any kdrama show
2. Click on any of the episodes
3. Select any of the available sources
4. ResolveURL pops up

**Log file**
Generated Error from Log
```
2024-06-02 17:28:38.028 T:11695780   error <general>: ResolveURL: AttributeError Error - From: dembed2 Link: https://streamcool.pro/streaming.php?id=NDExNDI0&title=Beauty+and+Mr.+Romantic+%282024%29+episode+21&typesub=SUB: 'bytes' object has no attribute 'encode'
```

**Comment by AcidSlide** [comment]
Additional note, I was able to use DramaCool (3.2.9) a few days ago.  Only thing that was changed/updated lately was the ResolveURL.

This is happening to all my Kodi setups.

**Comment by groggyegg** [comment]
It should work with other mirrors

**Comment by groggyegg** [comment]
Have created an issue in ResolveUrl repo and hopefully it will be fixed there.
