### ISSUE TITLE
ResolveURL Failed

### ISSUE THREAD

**Issue by rahaaatul** [groggyegg/plugin.video.dramacool#80]
**Describe the bug**
Can't play any drama, gives `ResolveURL Failed` error.

> [!Note]
> Can play those same dramas on browser.

**To Reproduce**
1. Go to 'Recently Added Drama'.
2. Play any drama.
3. See error.

**Screen Recording**

https://github.com/user-attachments/assets/e66f69e4-a5ec-4e15-8d2e-6a1cb84051b1

**Log file**
[kodi.log](https://github.com/user-attachments/files/16482979/kodi.log)

**Comment by minhgi** [comment]
I have the same issue

**Comment by rahaaatul** [comment]
Bumping @groggyegg

**Comment by groggyegg** [comment]
Only standard server and asianload affected, other mirrors should work when available. I think only the domain needs to be updated in ResolveURL but will do it when I have time.

**Comment by jasonhoblack** [comment]
Having the same issue unfortunately.

Please keep us updated when you have time.

Take care
