### ISSUE TITLE
have a label ListItem.TVShowTitle for shows

### ISSUE THREAD

**Issue by hcgiub001** [groggyegg/plugin.video.dramacool#81]
hey groggyegg, thanks for your time.

I'm trying to create a script that identifies if an item is a movie or a show and then uses Fen Light to search for it. I love dramacool, best Asian drama/movie addon but sometimes the quality isn't as good as torrents so I can quickly search inside Fen Light. I created a script that I can see allot of the properties and for an item in dramacool I get this data

> ListItem.Label: 1x01. [SUB] Goblin (2016)
> ListItem.Title: [SUB] Goblin (2016)
> ListItem.OriginalTitle: 
> ListItem.TVShowTitle: 
> ListItem.Season: 1
> ListItem.Episode: 1
> ListItem.Year: 
> ListItem.Rating: 
> ListItem.Votes: 0
> ListItem.Genre: 
> ListItem.Director: 
> ListItem.Writer: 
> ListItem.Plot: 
> ListItem.PlotOutline: 
> ListItem.Tagline: 
> ListItem.Studio: 
> ListItem.MPAA: 
> ListItem.Cast: 
> ListItem.Country: 
> ListItem.Premiered: 
> ListItem.FirstAired: ListItem.FirstAired
> ListItem.LastPlayed: 
> ListItem.PlayCount: 
> ListItem.Path: plugin://plugin.video.dramacool/
> ListItem.Filename: goblin-episode-1.html
> ListItem.FileSize: ListItem.FileSize
> ListItem.DateAdded: 
> ListItem.IMDBNumber: 
> ListItem.TMDBNumber: ListItem.TMDBNumber
> ListItem.TVDBNumber: ListItem.TVDBNumber
> ListItem.Art(poster): 
> ListItem.Art(fanart): 
> ListItem.Art(thumb): 
> ListItem.Art(banner): 
> ListItem.Art(clearart): 
> ListItem.Art(landscape): 
> ListItem.Art(discart): 
> ListItem.Art(logos): 
> ListItem.Art(keyart): 
> ListItem.Art(characterart): 
> Container.PluginName: plugin.video.dramacool

will it be possible that you use the property ListItem.TVShowTitle
for each item that is a TVShow, this could be the same as the > ListItem.Title
for the example above for Goblin you could have

> ListItem.Title: [SUB] Goblin (2016)
> ListItem.TVShowTitle: Goblin

I'd like it when it's over a show and in the episodes,
![image](https://github.com/user-attachments/assets/4acc3c2e-dfc6-450c-b9b7-af9a28d4f4ee)
![image](https://github.com/user-attachments/assets/c5c2d360-8691-4f44-9555-1530736af966)

this would also allow a way for skinners to correctly label it so in Nimbus here is recently added movie
![image](https://github.com/user-attachments/assets/f14c166a-c0b6-462e-b844-ae446709bb91)

their is no way to know if it's a TV show or a Movie so Nimbus incorrectly labels this section as TV Shows. with this enhancement we can get the right label

thanks for your consideration

**Comment by groggyegg** [comment]
Should be possible but not a priority since the code will be rewritten in the future. But I welcome any PR that fix this as a short term solution.

**Comment by hcgiub001** [comment]
thanks for getting back to me, I learnt from the developer that to fix this issue

> What's missing there  is a plugin category. This is what Nimbus uses to display that kind of information. It pulls it using this infolabel $INFO[Container.PluginCategory].
> 
> If the information you want is stored in a different infolabel, I can add that in

if you can consider this in the future when you do a rewrite, that would be awesome :)
I can't code so can't help but I'll look forward to the update in the future so for now I'll close the issue. thanks
