### ISSUE TITLE
Dramacool error 

### ISSUE THREAD

**Issue by Noryuen** [groggyegg/plugin.video.dramacool#84]
Recently updated Kodi to v21, dramacool could not access the show. When click on the ' kshow ' and search any one of the show , it gave me this 'Nonetype' object has no attribute 'text' error message. 
Can anyone help on how solve it?
TIA

**Comment by Noryuen** [comment]
Thank you.  Yes, with your guidance it works. Very much appreciated.

**Comment by Noryuen** [comment]
I apologise to ask again.
After changing the domains name , however, the drama series are not updated. It seems to be stagnated.
How to solve?  Any help? TIA

**Comment by groggyegg** [comment]
https://github.com/groggyegg/plugin.video.dramacool/issues/82
